name: tabor_chat
description: Simple websocket chat.
publish_to: 'none'

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.2.1

dependencies:
  flutter:
    sdk: flutter

  #BLoC
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  provider: ^5.0.0

  #Router
  mad_navigator:
    path: ./packages/mad_navigator
  path_to_regexp: ^0.4.0

  #Localization
  intl: ^0.17.0
  easy_localization: ^3.0.0
  flutter_localizations:
    sdk: flutter

  #Injections
  get_it: ^7.1.3
  injectable: ^1.4.1

  #Network
  dio: ^4.0.0
  connectivity: ^3.0.6

  #Others
  flutter_svg: ^0.22.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  json_annotation: ^4.0.1
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

  #Native generators
  flutter_native_splash: ^1.1.8+4
  #flutter_launcher_icons: ^0.9.0

  #Injections
  injectable_generator: ^1.4.1

# Настройки сплэш скрина
flutter_native_splash:
  image: "resources/splash/splash.png"
  color: "ffffff"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/fonts/cuprum/
  fonts:
    - family: Cuprum
      fonts:
        - asset: assets/fonts/cuprum/Cuprum-Regular.ttf
          weight: 400
        - asset: assets/fonts/cuprum/Cuprum-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/cuprum/Cuprum-Medium.ttf
          weight: 500
        - asset: assets/fonts/cuprum/Cuprum-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/cuprum/Cuprum-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cuprum/Cuprum-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/cuprum/Cuprum-Bold.ttf
          weight: 700
        - asset: assets/fonts/cuprum/Cuprum-BoldItalic.ttf
          weight: 700
          style: italic